services:
    sda5f_ws:
        build: docker/sda5f
        container_name: sda5f_container
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
            - ROS_HOSTNAME=localhost
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ./catkin_ws/src/sda5f_motion_plan:/catkin_ws/src/sda5f_motion_plan
            - ./catkin_ws/src/sda5f_stack:/catkin_ws/src/sda5f_stack
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/noetic/setup.bash && catkin build -DPYTHON_EXECUTABLE=/usr/bin/python3 && bash"
